package com.etoak.mapper;

import com.etoak.bean.MovieReview;
import com.etoak.bean.MovieReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int countByExample(MovieReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int deleteByExample(MovieReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int insert(MovieReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int insertSelective(MovieReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    List<MovieReview> selectByExample(MovieReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    MovieReview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") MovieReview record, @Param("example") MovieReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int updateByExample(@Param("record") MovieReview record, @Param("example") MovieReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int updateByPrimaryKeySelective(MovieReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_review
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    int updateByPrimaryKey(MovieReview record);
}