package com.etoak.mapper;

import com.etoak.bean.Movie;
import com.etoak.bean.MovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int countByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int deleteByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int deleteByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int insertSelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    List<Movie> selectByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    Movie selectByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int updateByExample(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int updateByPrimaryKeySelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    int updateByPrimaryKey(Movie record);
}