package com.etoak.bean;

public class Movie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_id
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private Integer movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_name
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_director
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieDirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_actor
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieActor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_type
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_area
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_language
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_ontime
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieOntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_pic
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String moviePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_operation
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private Integer movieOperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_movie.movie_create
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    private String movieCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_id
     *
     * @return the value of eve_movie.movie_id
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_id
     *
     * @param movieId the value for eve_movie.movie_id
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_name
     *
     * @return the value of eve_movie.movie_name
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieName() {
        return movieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_name
     *
     * @param movieName the value for eve_movie.movie_name
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieName(String movieName) {
        this.movieName = movieName == null ? null : movieName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_director
     *
     * @return the value of eve_movie.movie_director
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieDirector() {
        return movieDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_director
     *
     * @param movieDirector the value for eve_movie.movie_director
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieDirector(String movieDirector) {
        this.movieDirector = movieDirector == null ? null : movieDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_actor
     *
     * @return the value of eve_movie.movie_actor
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieActor() {
        return movieActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_actor
     *
     * @param movieActor the value for eve_movie.movie_actor
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieActor(String movieActor) {
        this.movieActor = movieActor == null ? null : movieActor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_type
     *
     * @return the value of eve_movie.movie_type
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieType() {
        return movieType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_type
     *
     * @param movieType the value for eve_movie.movie_type
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieType(String movieType) {
        this.movieType = movieType == null ? null : movieType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_area
     *
     * @return the value of eve_movie.movie_area
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieArea() {
        return movieArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_area
     *
     * @param movieArea the value for eve_movie.movie_area
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieArea(String movieArea) {
        this.movieArea = movieArea == null ? null : movieArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_language
     *
     * @return the value of eve_movie.movie_language
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieLanguage() {
        return movieLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_language
     *
     * @param movieLanguage the value for eve_movie.movie_language
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieLanguage(String movieLanguage) {
        this.movieLanguage = movieLanguage == null ? null : movieLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_ontime
     *
     * @return the value of eve_movie.movie_ontime
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieOntime() {
        return movieOntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_ontime
     *
     * @param movieOntime the value for eve_movie.movie_ontime
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieOntime(String movieOntime) {
        this.movieOntime = movieOntime == null ? null : movieOntime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_pic
     *
     * @return the value of eve_movie.movie_pic
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMoviePic() {
        return moviePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_pic
     *
     * @param moviePic the value for eve_movie.movie_pic
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMoviePic(String moviePic) {
        this.moviePic = moviePic == null ? null : moviePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_operation
     *
     * @return the value of eve_movie.movie_operation
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public Integer getMovieOperation() {
        return movieOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_operation
     *
     * @param movieOperation the value for eve_movie.movie_operation
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieOperation(Integer movieOperation) {
        this.movieOperation = movieOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_movie.movie_create
     *
     * @return the value of eve_movie.movie_create
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getMovieCreate() {
        return movieCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_movie.movie_create
     *
     * @param movieCreate the value for eve_movie.movie_create
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setMovieCreate(String movieCreate) {
        this.movieCreate = movieCreate == null ? null : movieCreate.trim();
    }
}