package com.etoak.bean;

public class MovieReview {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_review.id
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_review.content
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_review.username
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_review.movie_id
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    private Integer movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eve_review.review_create
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    private String reviewCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_review.id
     *
     * @return the value of eve_review.id
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_review.id
     *
     * @param id the value for eve_review.id
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_review.content
     *
     * @return the value of eve_review.content
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_review.content
     *
     * @param content the value for eve_review.content
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_review.username
     *
     * @return the value of eve_review.username
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_review.username
     *
     * @param username the value for eve_review.username
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_review.movie_id
     *
     * @return the value of eve_review.movie_id
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_review.movie_id
     *
     * @param movieId the value for eve_review.movie_id
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eve_review.review_create
     *
     * @return the value of eve_review.review_create
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public String getReviewCreate() {
        return reviewCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eve_review.review_create
     *
     * @param reviewCreate the value for eve_review.review_create
     *
     * @mbggenerated Fri Nov 01 17:42:28 CST 2019
     */
    public void setReviewCreate(String reviewCreate) {
        this.reviewCreate = reviewCreate == null ? null : reviewCreate.trim();
    }
}