package com.etoak.bean;

import java.util.ArrayList;
import java.util.List;

public class MovieExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public MovieExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMovieIdIsNull() {
            addCriterion("movie_id is null");
            return (Criteria) this;
        }

        public Criteria andMovieIdIsNotNull() {
            addCriterion("movie_id is not null");
            return (Criteria) this;
        }

        public Criteria andMovieIdEqualTo(Integer value) {
            addCriterion("movie_id =", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotEqualTo(Integer value) {
            addCriterion("movie_id <>", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdGreaterThan(Integer value) {
            addCriterion("movie_id >", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_id >=", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdLessThan(Integer value) {
            addCriterion("movie_id <", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdLessThanOrEqualTo(Integer value) {
            addCriterion("movie_id <=", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdIn(List<Integer> values) {
            addCriterion("movie_id in", values, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotIn(List<Integer> values) {
            addCriterion("movie_id not in", values, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdBetween(Integer value1, Integer value2) {
            addCriterion("movie_id between", value1, value2, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_id not between", value1, value2, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieNameIsNull() {
            addCriterion("movie_name is null");
            return (Criteria) this;
        }

        public Criteria andMovieNameIsNotNull() {
            addCriterion("movie_name is not null");
            return (Criteria) this;
        }

        public Criteria andMovieNameEqualTo(String value) {
            addCriterion("movie_name =", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameNotEqualTo(String value) {
            addCriterion("movie_name <>", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameGreaterThan(String value) {
            addCriterion("movie_name >", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameGreaterThanOrEqualTo(String value) {
            addCriterion("movie_name >=", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameLessThan(String value) {
            addCriterion("movie_name <", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameLessThanOrEqualTo(String value) {
            addCriterion("movie_name <=", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameLike(String value) {
            addCriterion("movie_name like", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameNotLike(String value) {
            addCriterion("movie_name not like", value, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameIn(List<String> values) {
            addCriterion("movie_name in", values, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameNotIn(List<String> values) {
            addCriterion("movie_name not in", values, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameBetween(String value1, String value2) {
            addCriterion("movie_name between", value1, value2, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieNameNotBetween(String value1, String value2) {
            addCriterion("movie_name not between", value1, value2, "movieName");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorIsNull() {
            addCriterion("movie_director is null");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorIsNotNull() {
            addCriterion("movie_director is not null");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorEqualTo(String value) {
            addCriterion("movie_director =", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorNotEqualTo(String value) {
            addCriterion("movie_director <>", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorGreaterThan(String value) {
            addCriterion("movie_director >", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorGreaterThanOrEqualTo(String value) {
            addCriterion("movie_director >=", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorLessThan(String value) {
            addCriterion("movie_director <", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorLessThanOrEqualTo(String value) {
            addCriterion("movie_director <=", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorLike(String value) {
            addCriterion("movie_director like", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorNotLike(String value) {
            addCriterion("movie_director not like", value, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorIn(List<String> values) {
            addCriterion("movie_director in", values, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorNotIn(List<String> values) {
            addCriterion("movie_director not in", values, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorBetween(String value1, String value2) {
            addCriterion("movie_director between", value1, value2, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieDirectorNotBetween(String value1, String value2) {
            addCriterion("movie_director not between", value1, value2, "movieDirector");
            return (Criteria) this;
        }

        public Criteria andMovieActorIsNull() {
            addCriterion("movie_actor is null");
            return (Criteria) this;
        }

        public Criteria andMovieActorIsNotNull() {
            addCriterion("movie_actor is not null");
            return (Criteria) this;
        }

        public Criteria andMovieActorEqualTo(String value) {
            addCriterion("movie_actor =", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorNotEqualTo(String value) {
            addCriterion("movie_actor <>", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorGreaterThan(String value) {
            addCriterion("movie_actor >", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorGreaterThanOrEqualTo(String value) {
            addCriterion("movie_actor >=", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorLessThan(String value) {
            addCriterion("movie_actor <", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorLessThanOrEqualTo(String value) {
            addCriterion("movie_actor <=", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorLike(String value) {
            addCriterion("movie_actor like", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorNotLike(String value) {
            addCriterion("movie_actor not like", value, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorIn(List<String> values) {
            addCriterion("movie_actor in", values, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorNotIn(List<String> values) {
            addCriterion("movie_actor not in", values, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorBetween(String value1, String value2) {
            addCriterion("movie_actor between", value1, value2, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieActorNotBetween(String value1, String value2) {
            addCriterion("movie_actor not between", value1, value2, "movieActor");
            return (Criteria) this;
        }

        public Criteria andMovieTypeIsNull() {
            addCriterion("movie_type is null");
            return (Criteria) this;
        }

        public Criteria andMovieTypeIsNotNull() {
            addCriterion("movie_type is not null");
            return (Criteria) this;
        }

        public Criteria andMovieTypeEqualTo(String value) {
            addCriterion("movie_type =", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeNotEqualTo(String value) {
            addCriterion("movie_type <>", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeGreaterThan(String value) {
            addCriterion("movie_type >", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeGreaterThanOrEqualTo(String value) {
            addCriterion("movie_type >=", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeLessThan(String value) {
            addCriterion("movie_type <", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeLessThanOrEqualTo(String value) {
            addCriterion("movie_type <=", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeLike(String value) {
            addCriterion("movie_type like", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeNotLike(String value) {
            addCriterion("movie_type not like", value, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeIn(List<String> values) {
            addCriterion("movie_type in", values, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeNotIn(List<String> values) {
            addCriterion("movie_type not in", values, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeBetween(String value1, String value2) {
            addCriterion("movie_type between", value1, value2, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieTypeNotBetween(String value1, String value2) {
            addCriterion("movie_type not between", value1, value2, "movieType");
            return (Criteria) this;
        }

        public Criteria andMovieAreaIsNull() {
            addCriterion("movie_area is null");
            return (Criteria) this;
        }

        public Criteria andMovieAreaIsNotNull() {
            addCriterion("movie_area is not null");
            return (Criteria) this;
        }

        public Criteria andMovieAreaEqualTo(String value) {
            addCriterion("movie_area =", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaNotEqualTo(String value) {
            addCriterion("movie_area <>", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaGreaterThan(String value) {
            addCriterion("movie_area >", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaGreaterThanOrEqualTo(String value) {
            addCriterion("movie_area >=", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaLessThan(String value) {
            addCriterion("movie_area <", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaLessThanOrEqualTo(String value) {
            addCriterion("movie_area <=", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaLike(String value) {
            addCriterion("movie_area like", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaNotLike(String value) {
            addCriterion("movie_area not like", value, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaIn(List<String> values) {
            addCriterion("movie_area in", values, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaNotIn(List<String> values) {
            addCriterion("movie_area not in", values, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaBetween(String value1, String value2) {
            addCriterion("movie_area between", value1, value2, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieAreaNotBetween(String value1, String value2) {
            addCriterion("movie_area not between", value1, value2, "movieArea");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageIsNull() {
            addCriterion("movie_language is null");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageIsNotNull() {
            addCriterion("movie_language is not null");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageEqualTo(String value) {
            addCriterion("movie_language =", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageNotEqualTo(String value) {
            addCriterion("movie_language <>", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageGreaterThan(String value) {
            addCriterion("movie_language >", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("movie_language >=", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageLessThan(String value) {
            addCriterion("movie_language <", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageLessThanOrEqualTo(String value) {
            addCriterion("movie_language <=", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageLike(String value) {
            addCriterion("movie_language like", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageNotLike(String value) {
            addCriterion("movie_language not like", value, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageIn(List<String> values) {
            addCriterion("movie_language in", values, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageNotIn(List<String> values) {
            addCriterion("movie_language not in", values, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageBetween(String value1, String value2) {
            addCriterion("movie_language between", value1, value2, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieLanguageNotBetween(String value1, String value2) {
            addCriterion("movie_language not between", value1, value2, "movieLanguage");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeIsNull() {
            addCriterion("movie_ontime is null");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeIsNotNull() {
            addCriterion("movie_ontime is not null");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeEqualTo(String value) {
            addCriterion("movie_ontime =", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeNotEqualTo(String value) {
            addCriterion("movie_ontime <>", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeGreaterThan(String value) {
            addCriterion("movie_ontime >", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeGreaterThanOrEqualTo(String value) {
            addCriterion("movie_ontime >=", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeLessThan(String value) {
            addCriterion("movie_ontime <", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeLessThanOrEqualTo(String value) {
            addCriterion("movie_ontime <=", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeLike(String value) {
            addCriterion("movie_ontime like", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeNotLike(String value) {
            addCriterion("movie_ontime not like", value, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeIn(List<String> values) {
            addCriterion("movie_ontime in", values, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeNotIn(List<String> values) {
            addCriterion("movie_ontime not in", values, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeBetween(String value1, String value2) {
            addCriterion("movie_ontime between", value1, value2, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMovieOntimeNotBetween(String value1, String value2) {
            addCriterion("movie_ontime not between", value1, value2, "movieOntime");
            return (Criteria) this;
        }

        public Criteria andMoviePicIsNull() {
            addCriterion("movie_pic is null");
            return (Criteria) this;
        }

        public Criteria andMoviePicIsNotNull() {
            addCriterion("movie_pic is not null");
            return (Criteria) this;
        }

        public Criteria andMoviePicEqualTo(String value) {
            addCriterion("movie_pic =", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicNotEqualTo(String value) {
            addCriterion("movie_pic <>", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicGreaterThan(String value) {
            addCriterion("movie_pic >", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicGreaterThanOrEqualTo(String value) {
            addCriterion("movie_pic >=", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicLessThan(String value) {
            addCriterion("movie_pic <", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicLessThanOrEqualTo(String value) {
            addCriterion("movie_pic <=", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicLike(String value) {
            addCriterion("movie_pic like", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicNotLike(String value) {
            addCriterion("movie_pic not like", value, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicIn(List<String> values) {
            addCriterion("movie_pic in", values, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicNotIn(List<String> values) {
            addCriterion("movie_pic not in", values, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicBetween(String value1, String value2) {
            addCriterion("movie_pic between", value1, value2, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMoviePicNotBetween(String value1, String value2) {
            addCriterion("movie_pic not between", value1, value2, "moviePic");
            return (Criteria) this;
        }

        public Criteria andMovieOperationIsNull() {
            addCriterion("movie_operation is null");
            return (Criteria) this;
        }

        public Criteria andMovieOperationIsNotNull() {
            addCriterion("movie_operation is not null");
            return (Criteria) this;
        }

        public Criteria andMovieOperationEqualTo(Integer value) {
            addCriterion("movie_operation =", value, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationNotEqualTo(Integer value) {
            addCriterion("movie_operation <>", value, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationGreaterThan(Integer value) {
            addCriterion("movie_operation >", value, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_operation >=", value, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationLessThan(Integer value) {
            addCriterion("movie_operation <", value, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationLessThanOrEqualTo(Integer value) {
            addCriterion("movie_operation <=", value, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationIn(List<Integer> values) {
            addCriterion("movie_operation in", values, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationNotIn(List<Integer> values) {
            addCriterion("movie_operation not in", values, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationBetween(Integer value1, Integer value2) {
            addCriterion("movie_operation between", value1, value2, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieOperationNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_operation not between", value1, value2, "movieOperation");
            return (Criteria) this;
        }

        public Criteria andMovieCreateIsNull() {
            addCriterion("movie_create is null");
            return (Criteria) this;
        }

        public Criteria andMovieCreateIsNotNull() {
            addCriterion("movie_create is not null");
            return (Criteria) this;
        }

        public Criteria andMovieCreateEqualTo(String value) {
            addCriterion("movie_create =", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateNotEqualTo(String value) {
            addCriterion("movie_create <>", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateGreaterThan(String value) {
            addCriterion("movie_create >", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateGreaterThanOrEqualTo(String value) {
            addCriterion("movie_create >=", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateLessThan(String value) {
            addCriterion("movie_create <", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateLessThanOrEqualTo(String value) {
            addCriterion("movie_create <=", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateLike(String value) {
            addCriterion("movie_create like", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateNotLike(String value) {
            addCriterion("movie_create not like", value, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateIn(List<String> values) {
            addCriterion("movie_create in", values, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateNotIn(List<String> values) {
            addCriterion("movie_create not in", values, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateBetween(String value1, String value2) {
            addCriterion("movie_create between", value1, value2, "movieCreate");
            return (Criteria) this;
        }

        public Criteria andMovieCreateNotBetween(String value1, String value2) {
            addCriterion("movie_create not between", value1, value2, "movieCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eve_movie
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 01 17:30:39 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eve_movie
     *
     * @mbggenerated Fri Nov 01 17:30:39 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}